# Generated by Django 4.2 on 2023-04-14 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_shoppingcart_amount'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='shoppingcart',
            constraint=models.UniqueConstraint(fields=('buyer', 'product'), name='Unique product with buyer'),
        ),
    ]
